#!/usr/bin/env bash
# Installs Nginx with the following configurations:
#   Listens on port 80.
#   When queried, Returns a page containing "Hello World!",
#   at the root with a curl GET request.

sudo apt-get -y update
sudo apt-get -y install nginx
echo 'Hello World!' > /var/www/html/index.html

sudo service nginx restart
